// Register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

// Logout
export const USER_LOGOUT = 'USER_LOGOUT'

// PETS
export const PET_LIST_REQUEST = 'PET_LIST_REQUEST'
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS'
export const PET_LIST_FAIL = 'PET_LIST_FAIL'

export const PET_MY_LIST_REQUEST = 'PET_MY_LIST_REQUEST'
export const PET_MY_LIST_SUCCESS = 'PET_MY_LIST_SUCCESS'
export const PET_MY_LIST_FAIL = 'PET_MY_LIST_FAIL'

export const PET_DETAILS_REQUEST = 'PET_DETAILS_REQUEST'
export const PET_DETAILS_SUCCESS = 'PET_DETAILS_SUCCESS'
export const PET_DETAILS_FAIL = 'PET_DETAILS_FAIL'

export const PET_CREATE_REQUEST = 'PET_CREATE_REQUEST'
export const PET_CREATE_SUCCESS = 'PET_CREATE_SUCCESS'
export const PET_CREATE_FAIL = 'PET_CREATE_FAIL'

export const PET_UPDATE_REQUEST = 'PET_UPDATE_REQUEST'
export const PET_UPDATE_SUCCESS = 'PET_UPDATE_SUCCESS'
export const PET_UPDATE_FAIL = 'PET_UPDATE_FAIL'

export const PET_DELETE_REQUEST = 'PET_DELETE_REQUEST'
export const PET_DELETE_SUCCESS = 'PET_DELETE_SUCCESS'
export const PET_DELETE_FAIL = 'PET_DELETE_FAIL'
