// Register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

// Logout
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

// ADMIN
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'
export const USER_CREATE_RESET = 'USER_CREATE_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

// PETS
export const PET_LIST_REQUEST = 'PET_LIST_REQUEST'
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS'
export const PET_LIST_FAIL = 'PET_LIST_FAIL'

export const PET_MY_LIST_REQUEST = 'PET_MY_LIST_REQUEST'
export const PET_MY_LIST_SUCCESS = 'PET_MY_LIST_SUCCESS'
export const PET_MY_LIST_FAIL = 'PET_MY_LIST_FAIL'

export const PET_DETAILS_REQUEST = 'PET_DETAILS_REQUEST'
export const PET_DETAILS_SUCCESS = 'PET_DETAILS_SUCCESS'
export const PET_DETAILS_FAIL = 'PET_DETAILS_FAIL'

export const PET_CREATE_REQUEST = 'PET_CREATE_REQUEST'
export const PET_CREATE_SUCCESS = 'PET_CREATE_SUCCESS'
export const PET_CREATE_FAIL = 'PET_CREATE_FAIL'
export const PET_CREATE_RESET = 'PET_CREATE_RESET'

export const PET_UPDATE_REQUEST = 'PET_UPDATE_REQUEST'
export const PET_UPDATE_SUCCESS = 'PET_UPDATE_SUCCESS'
export const PET_UPDATE_FAIL = 'PET_UPDATE_FAIL'
export const PET_UPDATE_RESET = 'PET_UPDATE_RESET'

export const PET_DELETE_REQUEST = 'PET_DELETE_REQUEST'
export const PET_DELETE_SUCCESS = 'PET_DELETE_SUCCESS'
export const PET_DELETE_FAIL = 'PET_DELETE_FAIL'

// EVENTS
export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL'

export const EVENT_MY_LIST_REQUEST = 'EVENT_MY_LIST_REQUEST'
export const EVENT_MY_LIST_SUCCESS = 'EVENT_MY_LIST_SUCCESS'
export const EVENT_MY_LIST_FAIL = 'EVENT_MY_LIST_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'

export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST'
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS'
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL'
export const EVENT_CREATE_RESET = 'EVENT_CREATE_RESET'

export const EVENT_UPDATE_REQUEST = 'EVENT_UPDATE_REQUEST'
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS'
export const EVENT_UPDATE_FAIL = 'EVENT_UPDATE_FAIL'
export const EVENT_UPDATE_RESET = 'EVENT_UPDATE_RESET'

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST'
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS'
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL'

// DONATIONS
export const DONATION_LIST_REQUEST = 'DONATION_LIST_REQUEST'
export const DONATION_LIST_SUCCESS = 'DONATION_LIST_SUCCESS'
export const DONATION_LIST_FAIL = 'DONATION_LIST_FAIL'

export const DONATION_MY_LIST_REQUEST = 'DONATION_MY_LIST_REQUEST'
export const DONATION_MY_LIST_SUCCESS = 'DONATION_MY_LIST_SUCCESS'
export const DONATION_MY_LIST_FAIL = 'DONATION_MY_LIST_FAIL'

export const DONATION_DETAILS_REQUEST = 'DONATION_DETAILS_REQUEST'
export const DONATION_DETAILS_SUCCESS = 'DONATION_DETAILS_SUCCESS'
export const DONATION_DETAILS_FAIL = 'DONATION_DETAILS_FAIL'

export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST'
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS'
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL'
export const DONATION_CREATE_RESET = 'DONATION_CREATE_RESET'

export const DONATION_UPDATE_REQUEST = 'DONATION_UPDATE_REQUEST'
export const DONATION_UPDATE_SUCCESS = 'DONATION_UPDATE_SUCCESS'
export const DONATION_UPDATE_FAIL = 'DONATION_UPDATE_FAIL'
export const DONATION_UPDATE_RESET = 'DONATION_UPDATE_RESET'

export const DONATION_DELETE_REQUEST = 'DONATION_DELETE_REQUEST'
export const DONATION_DELETE_SUCCESS = 'DONATION_DELETE_SUCCESS'
export const DONATION_DELETE_FAIL = 'DONATION_DELETE_FAIL'

// VOLUNTEERS
export const VOLUNTEER_LIST_REQUEST = 'VOLUNTEER_LIST_REQUEST'
export const VOLUNTEER_LIST_SUCCESS = 'VOLUNTEER_LIST_SUCCESS'
export const VOLUNTEER_LIST_FAIL = 'VOLUNTEER_LIST_FAIL'

export const VOLUNTEER_MY_LIST_REQUEST = 'VOLUNTEER_MY_LIST_REQUEST'
export const VOLUNTEER_MY_LIST_SUCCESS = 'VOLUNTEER_MY_LIST_SUCCESS'
export const VOLUNTEER_MY_LIST_FAIL = 'VOLUNTEER_MY_LIST_FAIL'

export const VOLUNTEER_DETAILS_REQUEST = 'VOLUNTEER_DETAILS_REQUEST'
export const VOLUNTEER_DETAILS_SUCCESS = 'VOLUNTEER_DETAILS_SUCCESS'
export const VOLUNTEER_DETAILS_FAIL = 'VOLUNTEER_DETAILS_FAIL'

export const VOLUNTEER_CREATE_REQUEST = 'VOLUNTEER_CREATE_REQUEST'
export const VOLUNTEER_CREATE_SUCCESS = 'VOLUNTEER_CREATE_SUCCESS'
export const VOLUNTEER_CREATE_FAIL = 'VOLUNTEER_CREATE_FAIL'
export const VOLUNTEER_CREATE_RESET = 'VOLUNTEER_CREATE_RESET'

export const VOLUNTEER_UPDATE_REQUEST = 'VOLUNTEER_UPDATE_REQUEST'
export const VOLUNTEER_UPDATE_SUCCESS = 'VOLUNTEER_UPDATE_SUCCESS'
export const VOLUNTEER_UPDATE_FAIL = 'VOLUNTEER_UPDATE_FAIL'
export const VOLUNTEER_UPDATE_RESET = 'VOLUNTEER_UPDATE_RESET'

export const VOLUNTEER_DELETE_REQUEST = 'VOLUNTEER_DELETE_REQUEST'
export const VOLUNTEER_DELETE_SUCCESS = 'VOLUNTEER_DELETE_SUCCESS'
export const VOLUNTEER_DELETE_FAIL = 'VOLUNTEER_DELETE_FAIL'

// QUESTIONS
export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL'

export const QUESTION_MY_LIST_REQUEST = 'QUESTION_MY_LIST_REQUEST'
export const QUESTION_MY_LIST_SUCCESS = 'QUESTION_MY_LIST_SUCCESS'
export const QUESTION_MY_LIST_FAIL = 'QUESTION_MY_LIST_FAIL'

export const QUESTION_DETAILS_REQUEST = 'QUESTION_DETAILS_REQUEST'
export const QUESTION_DETAILS_SUCCESS = 'QUESTION_DETAILS_SUCCESS'
export const QUESTION_DETAILS_FAIL = 'QUESTION_DETAILS_FAIL'

export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'
export const QUESTION_CREATE_RESET = 'QUESTION_CREATE_RESET'

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST'
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS'
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL'
export const QUESTION_UPDATE_RESET = 'QUESTION_UPDATE_RESET'

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL'
